### ISSUE TITLE
과제에 대한 질문

### ISSUE THREAD

**Issue by kmsbernard** [HongDuHyeon/diary_minding#1]
## 1.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/features/Write/Write.tsx#L6

여기서 모듈스코프 변수를 일종의 상태로 사용하고 있는듯 합니다. React 컴포넌트의 상태(state)와 비교했을 때 어떤 차이점이 있고, 이렇게 구현된 이유는 무엇일까요?

## 2.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/components/ContentsWrapper.tsx#L4-L10

`React.FC` 타입을 사용하면 `childProps` 인터페이스를 별도로 선언하지 않아도 될 것 같습니다. React 내장 타입을 사용하지 않은 특별한 이유가 있을까요?

## 3.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/features/Detail/Detail.tsx#L37

종종 React Fragment가 최상위 요소 위에 한번 더 등장하는 경우가 보이는데요, 여기에는 어떤 의도가 있을까요?

## 4.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/features/Write/Write.tsx#L36-L38

여기서 `e.preventDefault();`는 어떤 역할을 하는 걸까요?

**Comment by HongDuHyeon** [comment]
1.
state는 값이 바뀔때마다 렌더링이 일어나지만 모듈스코프 변수를 사용하게 된다면 값이 바뀌고 렌더링이 일어나더라도 제가 작성했던 그 값이 변하지 않는다는 차이점이 있었고 
서버에 보내는 id 값이 겹칠 수도 있을 것 같다 판단하여 값이 바뀌어도 렌더링이 되지 않는 모듈 스코프 변수로 작성했습니다.
2.
 아직 타입스크립트 FC 부분에 대해 깊게 알지 못해서 평소에 children을 작성하던 방식대로 작업을 했습니다. 
3.
React Fragment는 형제 요소들을 묶어주기 위해 사용해주는데, 지금 코드에선 React Fragment가 필요한 페이지를 작업하면서 습관적으로 사용한 것 같습니다.
4.
onDiaryPost()를 작성하면서 form 태그를 이용해서 onSubmit으로 실행하는 동작과 onClick 동작 두개를 작성해보면서 미처 지우지 못한 것 같습니다.

-----Original Message-----
From: "Minsik ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2022-07-12 (화) 12:34:41 (GMT+09:00)
Subject: [HongDuHyeon/diary_minding] 과제에 대한 질문 (Issue #1)
 
1.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/features/Write/Write.tsx#L6
여기서 모듈스코프 변수를 일종의 상태로 사용하고 있는듯 합니다. React 컴포넌트의 상태(state)와 비교했을 때 어떤 차이점이 있고, 이렇게 구현된 이유는 무엇일까요?
2.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/components/ContentsWrapper.tsx#L4-L10
React.FC 타입을 사용하면 childProps 인터페이스를 별도로 선언하지 않아도 될 것 같습니다. React 내장 타입을 사용하지 않은 특별한 이유가 있을까요?
3.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/features/Detail/Detail.tsx#L37
종종 React Fragment가 최상위 요소 위에 한번 더 등장하는 경우가 보이는데요, 여기에는 어떤 의도가 있을까요?
4.
https://github.com/HongDuHyeon/diary_minding/blob/b402b021a72af60161199ef176cf84aadb2678a8/src/features/Write/Write.tsx#L36-L38
여기서 e.preventDefault();는 어떤 역할을 하는 걸까요?

**Comment by HongDuHyeon** [comment]
1.
state는 값이 바뀔때마다 렌더링이 일어나지만 모듈스코프 변수를 사용하게 된다면 값이 바뀌고 렌더링이 일어나더라도 제가 작성했던 그 값이 변하지 않는다는 차이점이 있었고
서버에 보내는 id 값이 겹칠 수도 있을 것 같다 판단하여 값이 바뀌어도 렌더링이 되지 않는 모듈 스코프 변수로 작성했습니다.
2.
 아직 타입스크립트 FC 부분에 대해 깊게 알지 못해서 평소에 children을 작성하던 방식대로 작업을 했습니다.
3.
React Fragment는 형제 요소들을 묶어주기 위해 사용해주는데, 지금 코드에선 React Fragment가 필요한 페이지를 작업하면서 습관적으로 사용한 것 같습니다.
4.
onDiaryPost()를 작성하면서 form 태그를 이용해서 onSubmit으로 실행하는 동작과 onClick 동작 두개를 작성해보면서 미처 지우지 못한 것 같습니다.
